with cte as
(
    select
    cast(REGEXP_EXTRACT(CourierID,r'[0-9]+') as int) Courier_ID,
    cast(concat(REGEXP_EXTRACT(DateReceived,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(DateReceived,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(DateReceived,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) DateReceived,
    CourierStatus,
    OrderStatus,
    GuideStatus,
    ModelStatus,
    DoctorName,
    ROI,
    UpperArch,
    LowerArch,
    GuideReprintJustification,
    cast(concat(REGEXP_EXTRACT(LastUpdate,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(LastUpdate,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(LastUpdate,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) LastUpdate,
    RadiologyService,
    ConversionService,
    PrintService,
    TreatmentService,
    GuideService,
    AnatomicCase,
    WaxupDesignStatus,
    BillingStatus,
    EstimatedTotal,
   cast(concat(REGEXP_EXTRACT(DateTreatmentPlanned,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(DateTreatmentPlanned,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(DateTreatmentPlanned,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) DateTreatmentPlanned,
    cast(concat(REGEXP_EXTRACT(DateScheduledForReview,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(DateScheduledForReview,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(DateScheduledForReview,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) DateScheduledForReview,
   cast(concat(REGEXP_EXTRACT(DatePendingApproval,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(DatePendingApproval,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(DatePendingApproval,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) DatePendingApproval,
   cast(concat(REGEXP_EXTRACT(DateOnHold,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(DateOnHold,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(DateOnHold,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) DateOnHold,
   cast(concat(REGEXP_EXTRACT(DateOnOrder,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(DateOnOrder,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(DateOnOrder,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) DateOnOrder,
   cast(concat(REGEXP_EXTRACT(DateReadyToPrint,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(DateReadyToPrint,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(DateReadyToPrint,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) DateReadyToPrint,
   cast(concat(REGEXP_EXTRACT(DatePrinting,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(DatePrinting,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(DatePrinting,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) DatePrinting,
   cast(concat(REGEXP_EXTRACT(DateReadyToDesign,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(DateReadyToDesign,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(DateReadyToDesign,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) DateReadyToDesign,
   cast(concat(REGEXP_EXTRACT(DateWaxupDesigned,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(DateWaxupDesigned,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(DateWaxupDesigned,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) DateWaxupDesigned,
   cast(concat(REGEXP_EXTRACT(DateDesigned,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(DateDesigned,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(DateDesigned,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) DateDesigned,
   cast(concat(REGEXP_EXTRACT(DateShipped,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(DateShipped,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(DateShipped,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) DateShipped,
   cast(concat(REGEXP_EXTRACT(DateSTLShared,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(DateSTLShared,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(DateSTLShared,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) DateSTLShared,
   cast(concat(REGEXP_EXTRACT(ApprovalReviewDate,r'\d\d?/\d\d?/(\d\d\d\d)'),'-',REGEXP_EXTRACT(ApprovalReviewDate,r'(\d\d?)/\d\d?/\d\d\d\d'),'-',
    REGEXP_EXTRACT(ApprovalReviewDate,r'\d\d?/(\d\d?)/\d\d\d\d')) as date) ApprovalReviewDate,
    LineItems,
    taxtotal,
    shippingcost,
    IsRush

    from {{source('RawData','stg_orders')}}
)select * from cte